function [ checkBool ] = checkStatisticObj( statisticObj )
%CHECKSETTINGS Summary of this function goes here
%   Detailed explanation goes here
if ~iscell(statisticObj)
    checkBool = false;
    return
elseif any(size(statisticObj,1) ~= 1 || size(statisticObj,2) == 0 ||...
        size(statisticObj,2) > 3)
    checkBool = false;
    return
elseif ~testNum(statisticObj{1}, 'int', [1, 3], [1, 1], [0, 2])
    checkBool = false;
    return
elseif numel(statisticObj{1}) == 2
    if statisticObj{1}(1) == statisticObj{1}(2) || ...
            (statisticObj{1}(1) ~= 3 && statisticObj{1}(2) ~= 3)
        checkBool = false;
        return
    end
end
for k = 2:length(statisticObj{1})+1
    statisticNr = statisticObj{1}(k-1);
    switch statisticNr
        case 1
            fieldNames = {'statisticNr',...
                          'vDesList',...
                          'vDesIndex',...
                          'averageIndex',...
                          'averageN',...
                          'timeNeeded'};
            if isfield(statisticObj{k}, fieldNames)
                 if any(~testNum(statisticObj{k}.statisticNr, 'int', [1,1], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.vDesList, 'double', [-inf,inf], [1, 1], [1,inf]) ||...
                         ~testNum(statisticObj{k}.vDesIndex, 'int', [1,1], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.averageIndex, 'int', [1,1], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.averageN, 'int', [1,inf], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.timeNeeded, 'double', [-inf,inf], [1, 1], [length(statisticObj{k}.vDesList),length(statisticObj{k}.vDesList)]))
                    checkBool = false;
                    return
                 end
            else
                checkBool = false;
                return
            end
        case 2
            fieldNames = {'statisticNr',...
                          'wallAngleList',...
                          'wallAngleIndex',...
                          'averageIndex',...
                          'averageN',...
                          'timeNeeded'};
             if isfield(statisticObj{k}, fieldNames)
                 if any(~testNum(statisticObj{k}.statisticNr, 'int', [2,2], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.wallAngleList, 'double', [0,pi/2], [1, 1], [1,inf]) ||...
                         ~testNum(statisticObj{k}.wallAngleIndex, 'int', [1,1], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.averageIndex, 'int', [1,1], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.averageN, 'int', [1,inf], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.timeNeeded, 'double', [-inf,inf], [1, 1], [length(statisticObj{k}.wallAngleList),length(statisticObj{k}.wallAngleList)]))
                    checkBool = false;
                    return
                 end
             else
                checkBool = false;
                return
             end
        case 3
            fieldNames = {'statisticNr',...
                          'timesAgentsThroughDoor',...
                          'hFig',...
                          'runN'};
             if isfield(statisticObj{k}, fieldNames)
                 if any(~testNum(statisticObj{k}.statisticNr, 'int', [3,3], [1, 1], [1,1]) ||...
                         ~testNum(statisticObj{k}.timesAgentsThroughDoor, 'double', [0,inf], [0, inf], [0,inf]) ||...
                         ~testNum(statisticObj{k}.hFig, 'double', [0,inf], [0, 1], [0,1]) ||...
                         ~testNum(statisticObj{k}.runN, 'int', [1,inf], [1, 1], [1,1]) )
                    checkBool = false;
                    return
                 end
             else
                checkBool = false;
                return
             end                
    end
end

checkBool = true;
end

