function [ validatedBool ] = validateSettings( settings )
%VALIDATESETTINGS validates if settings is of right format

fieldNames = {'A',...
            'B',...
            'k',...
            'kappa',...
            'tau',...
            'pressureBool',...
            'wallAngle',...
            'NAgent',...
            'border',...
            'yMax',...
            'doorWidth',...
            'density',...
            'vMeanAgentsIni',...
            'vVarAgentsIni',...
            'xMaxCalcBool',...
            'xMax',...
            'vDes',...
            'agentPositionStyle',...
            'agentPositionFilename',...
            'wallPositionStyle',...
            'wallPositionFilename',...
            'dt',...
            'dtPlot',...
    };
if isfield(settings, fieldNames)
    if validateNum(settings.A, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            validateNum(settings.B, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            validateNum(settings.k, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            validateNum(settings.kappa, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            validateNum(settings.tau, 'double', [0.001,inf], [1, 1], [1,1]) &&...
            islogical(settings.pressureBool) && numel(settings.pressureBool) == 1 &&...
            validateNum(settings.wallAngle, 'double', [0,90], [1, 1], [1,1]) &&...
            validateNum(settings.NAgent, 'int', [0,inf], [1, 1], [1,1]) &&...
            validateNum(settings.border, 'double', [0,inf], [1, 1], [1,1]) &&...
            validateNum(settings.yMax, 'double', [2.2*settings.border,inf], [1, 1], [1,1]) &&...
            validateNum(settings.doorWidth, 'double', [0,inf], [1, 1], [1,1]) &&...
            validateNum(settings.density, 'double', [0,inf], [1, 1], [1,1]) &&...
            validateNum(settings.vMeanAgentsIni, 'double', [0,inf], [1, 1], [1,1]) &&...
            validateNum(settings.vVarAgentsIni, 'double', [0,inf], [1, 1], [1,1]) &&...
            islogical(settings.xMaxCalcBool) && numel(settings.xMaxCalcBool) == 1 &&...
            validateNum(settings.xMax, 'double', [2*settings.border,inf], [1, 1], [1,1]) &&...
            validateNum(settings.vDes, 'double', [0,inf], [1, 1], [1,1]) &&...
            ischar(settings.agentPositionStyle) && ...
            (strcmp('randomLeftHalf', settings.agentPositionStyle) ||...
                strcmp('filename', settings.agentPositionStyle)) && ...
            ischar(settings.agentPositionFilename) && ...
            ischar(settings.wallPositionStyle) && ...
            (strcmp('standard', settings.wallPositionStyle) ||...
                strcmp('filename', settings.wallPositionStyle)) && ...
            validateNum(settings.dt, 'double', [0,inf], [1, 1], [1,1]) &&...
            validateNum(settings.dtPlot, 'double', [0,inf], [1, 1], [1,1])
        validatedBool = true;
        return
    end
end
validatedBool = false;

end

