function [ checkBool ] = checkSettings( settings )
%CHECKSETTINGS Summary of this function goes here
%   Detailed explanation goes here
fieldNames = {'A',...
            'B',...
            'k',...
            'kappa',...
            'tau',...
            'pressureBool',...
            'wallAngle',...
            'NAgent',...
            'border',...
            'yMax',...
            'doorWidth',...
            'density',...
            'vMeanAgentsIni',...
            'vVarAgentsIni',...
            'xMaxCalcBool',...
            'xMax',...
            'vDes',...
            'agentPositionStyle',...
            'agentPositionFilename',...
            'wallPositionStyle',...
            'wallPositionFilename',...
            'dt',...
            'dtPlot',...
    };
if isfield(settings, fieldNames)
    if testNum(settings.A, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            testNum(settings.B, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            testNum(settings.k, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            testNum(settings.kappa, 'double', [-inf,inf], [1, 1], [1,1]) &&...
            testNum(settings.tau, 'double', [0.001,inf], [1, 1], [1,1]) &&...
            islogical(settings.pressureBool) && numel(settings.pressureBool) == 1 &&...
            testNum(settings.wallAngle, 'double', [0,pi/2], [1, 1], [1,1]) &&...
            testNum(settings.NAgent, 'int', [0,inf], [1, 1], [1,1]) &&...
            testNum(settings.border, 'double', [0,inf], [1, 1], [1,1]) &&...
            testNum(settings.yMax, 'double', [2.2*settings.border,inf], [1, 1], [1,1]) &&...
            testNum(settings.doorWidth, 'double', [0,inf], [1, 1], [1,1]) &&...
            testNum(settings.density, 'double', [0,inf], [1, 1], [1,1]) &&...
            testNum(settings.vMeanAgentsIni, 'double', [0,inf], [1, 1], [1,1]) &&...
            testNum(settings.vVarAgentsIni, 'double', [0,inf], [1, 1], [1,1]) &&...
            islogical(settings.xMaxCalcBool) && numel(settings.xMaxCalcBool) == 1 &&...
            testNum(settings.xMax, 'double', [2*settings.border,inf], [1, 1], [1,1]) &&...
            testNum(settings.vDes, 'double', [0,inf], [1, 1], [1,1]) &&...
            ischar(settings.agentPositionStyle) && ...
            (strcmp('randomLeftHalf', settings.agentPositionStyle) ||...
                strcmp('filename', settings.agentPositionStyle)) && ...
            ischar(settings.agentPositionFilename) && ...
            ischar(settings.wallPositionStyle) && ...
            (strcmp('standard', settings.wallPositionStyle) ||...
                strcmp('filename', settings.wallPositionStyle)) && ...
            testNum(settings.dt, 'double', [0,inf], [1, 1], [1,1]) &&...
            testNum(settings.dtPlot, 'double', [0,inf], [1, 1], [1,1])
        checkBool = true;
        return
    end
end
checkBool = false;

end

