function automateObj = createAutomateObj( )
%CREATEAUTOMATEOBJ creates an automateObj, dependent on settings
%   exit times and current runs are stored in here
% see also: AUTOMATE, RESETAUTOMATEOBJ, DISPAUTOMATEOBJ

% (variable name, {{alias name, allowed value range, default range and step
%                   size, setter function, 'double' or 'int'}})
possibleAutomatedVariables = struct(...
    'none', {{'none', [0,0], [0,0,0], @(settings,val) '', 'double' }},...
    'vDes',{{'desired velocity',[0,inf], [1,6,0.5], @(settings,val) setfield(settings,'vDes',val), 'double' }},...
    'wallAngle', {{'wall angle', [0,90], [0, 90, 10], @(settings, val) setWallAngle(settings,val), 'double' }},...
    'NAgents',{{'number of agents', [0, inf], [10,110, 10], @(settings, val) setNAgent(settings,val), 'int' }},...
    'doorWidth',{{'door width', [0, inf], [1, 10, 0.5], @(settings,val) setfield(settings,'doorWidth',val),'double'}},...
    'density',{{'surface density of agents',[0.1,inf], [150,650,50], @(settings,val) setfield(settings,'density',val), 'double' }},...
    'A',{{'A',[-inf,inf], [1000,3000,500], @(settings,val) setfield(settings,'A',val), 'double' }},...
    'B',{{'B',[-inf,inf], [0.01,0.2,0.05], @(settings,val) setfield(settings,'B',val), 'double' }},...
    'k',{{'k',[-inf,inf], [0.2e5,2.2e5,0.5e5], @(settings,val) setfield(settings,'k',val), 'double' }},...
    'kappa',{{'kappa',[-inf,inf], [1.4e5,3.4e5,0.5e5], @(settings,val) setfield(settings,'kappa',val), 'double' }},...
    'tau',{{'tau',[0.001,inf], [0.1,1,0.1], @(settings,val) setfield(settings,'tau',val), 'double' }}...
    );
automateObj = struct(...
    'possibleAutomatedVariables', possibleAutomatedVariables,...
    'activeAutomatedVariable', 'none',...
    'plotIndividualExitTimesBool', true,...
    'variableRange', [],...
    'averageN', 1,...
    'rangeIndex', 1,...
    'averageIndex', 1,...
    'exitTimes', [],...
    'individualExitTimes', [],...
    'runN', 1,...
    'hFigIndividualExitTimes', []);
end

